#!/bin/bash
ADDRESS="https://github.com/HTTP410GONE/MacintoshPackager/releases/download/5.22duo/mpkg_5.22duo_duo.mpack"
MPKGLIVE="https://raw.githubusercontent.com/HTTP410GONE/MacintoshPackager/master/mpkg-live"
NETINSTALL="https://github.com/HTTP410GONE/MacintoshPackager/releases/download/Net1.1/net_1.1_darwin64-signed.mpack"
echo "NETINSTALL-LIVE"
echo "VERSION: 1.63"
echo "LAST UPDATE: JUNE.18.2019 KST 16:27:10"
echo "This will install: "
echo "mpkg 5.22 Duo"
echo "net 1.1"
echo "Checking architecture..."
if [[ -z $(uname -a | grep "Darwin") ]]; then
    echo "Architecture mismatch."
    exit 1
fi
echo "Downloading files..."
sudo curl -sL $ADDRESS > ~/mpkg.mpack
sudo curl -sL $MPKGLIVE > ~/mpkglive
sudo curl -sL $NETINSTALL > ~/net.mpack
sudo chmod +x ~/mpkglive
sudo ~/mpkglive -i ~/mpkg.mpack --override
sudo ~/mpkglive -i ~/net.mpack --override
sudo rm ~/mpkglive
sudo rm ~/net.mpack
sudo rm ~/mpkg.mpack
sudo rm ~/netlive
echo "Done."
