#!/bin/bash
ADDRESS="https://github.com/HTTP410GONE/MacintoshPackager/releases/download/7.1.1/mpkg_7.1.1_darwin64.mpack"
MPKGLIVE="https://raw.githubusercontent.com/HTTP410GONE/MacintoshPackager/master/mpkg-live"
NETINSTALL="https://github.com/HTTP410GONE/MacintoshPackager/releases/download/Net1.2/net_1.2_duo.mpack"
RED='\033[0;31m'
GRN='\033[0;32m'
BLU='\033[0;34m'
NC='\033[0m'
echo "NETINSTALL-LIVE"
echo "VERSION: 1.81"
echo "LAST UPDATE: SEP.29.2019"
echo "This will install: "
echo "mpkg 7.1.1 Darwin"
echo "net 1.2"
echo "Checking architecture..."
if [[ -z $(uname -a | grep "Darwin") ]]; then
    echo -e "${RED}Architecture mismatch.${NC}"
    exit 1
fi
echo "Downloading files..."
sudo curl -sL $ADDRESS > ~/mpkg.mpack
sudo curl -sL $MPKGLIVE > ~/mpkglive
sudo curl -sL $NETINSTALL > ~/net.mpack
sudo chmod +x ~/mpkglive
sudo mkdir /usr/local/mpkglib
sudo mkdir /usr/local/mpkglib/db
sudo ~/mpkglive -i ~/mpkg.mpack --override
sudo ~/mpkglive -i ~/net.mpack --override
sudo rm ~/mpkglive
sudo rm ~/net.mpack
sudo rm ~/mpkg.mpack
sudo rm ~/netlive
echo "${GRN}Done.${NC}"
