#!/bin/bash
pkg=$1
ROOTFS="/"
LIBRARY="/usr/local/mpkglib"

RED='\033[0;31m'
GRN='\033[0;32m'
YEL='\033[0;33m'
BLU='\033[0;34m'
NC='\033[0m'

if [[ -z "$pkg" ]]; then
	echo -e "${RED}Error: (35)${NC} No package specified!${NC}"
	exit
fi
echo "Package Info:"
echo "Name:" $(<$LIBRARY/db/"$pkg"/pkgname)
echo "ID:" $(<$LIBRARY/db/"$pkg"/pkgid)
echo "Version:" $(<$LIBRARY/db/"$pkg"/version)
exit